name: Run Danger on PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.repository == 'facebook/react-native'
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: ./.github/actions/setup-node
      - name: Run yarn
        uses: ./.github/actions/yarn-install-with-cache
      - name: Danger
        run: yarn danger ci --use-github-checks --failOnErrors
        working-directory: packages/react-native-bots
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.REACT_NATIVE_BOT_GITHUB_TOKEN }}
